const products= [
{
    //id:1,
    name: 'Eucalyptus Oil I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 675.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:2,
    name: 'Glycerin I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 65.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:3,
    name: 'Turpentine Oil I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 78.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:4,
    name: 'Castor Oil I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 72.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:5,
    name: 'Paraffin Oil I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 70.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:6,
    name: 'Methyl Salicylate I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 215.00,
    rating: 1,
    stock: 0,
    numReviews: 2 
},
{
    //id:7,
    name: 'Boric Ac//id I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 748.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:8,
    name: 'Soda bi carb I.P,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 22.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:9,
    name: 'Potassium permangabnate IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 100.00,
    rating: 1,
    stock: 10,
    numReviews: 2 
},
{
    //id:10,
    name: 'Zinc ox//ide IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 115.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:11,
    name: 'Purified talc IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 14.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:12,
    name: 'Mag-sulf IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 17.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:13,
    name: 'Sodium benzoate IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 64.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:14,
    name: 'Kaolin light IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 14.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:15,
    name: 'Isopropyl Rubbing alcohol USP,400gm',
    image: '/image/isopropyle_rubbing.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 50.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:16,
    name: 'Lint. Turpentile BP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 85.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:17,
    name: 'Prov//idone iodine IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 57.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:18,
    name: 'Calamine lotion IP,400gm',
    image: '/image/calamine_lotion.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 36.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:19,
    name: 'Jayscab lotion IP,400gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 68.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:20,
    name: 'Jaysedyl (cough linctus),100gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 288.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:21,
    name: 'Comp Benzoin Tin IP,400gm',
    image: '/image/benzoin_tincture.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 100.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:22,
    name: 'Iodine Tinctune USP,350ml',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 105.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:23,
    name: 'Jaylon (Antiseptic),100gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 114.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:24,
    name: 'Pov.lodine OINTMENT,200gm',
    image: '/image/savlon.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 68.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:25,
    name: 'squeaky clean (Hand sanitizer),500ml',
    image: '/image/squeaky_clean.jpg',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 90.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:26,
    name: 'Cologne water',
    image: '/image/',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 90.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
{
    //id:27,
    name: 'Lime Cologne water',
    image: '/image/',
    description: 'kkkkk',
    category: 'jui',
    brand: 'hi',
    price: 90.00,
    rating: 1,
    stock: 2,
    numReviews: 2 
},
]

module.exports = products


